export const TECHNOLOGIES = [
  {
    filename: "adobe_xd.svg",
    link: "https://www.adobe.com/ie/products/xd.html",
    title: "Adobe XD",
    id: "adobexd",
  },
  {
    filename: "android.svg",
    link: "https://www.android.com/intl/en_ie/",
    title: "Android",
    id: "android",
  },
  {
    filename: "android_studio.svg",
    link: "https://developer.android.com/studio",
    title: "Android Studio",
    id: "androidstudio",
  },
  {
    filename: "arduino.svg",
    link: "https://www.arduino.cc/",
    title: "Arduino",
    id: "arduino",
  },
  {
    filename: "aws.svg",
    link: "https://aws.amazon.com/",
    title: "Amazon Web Services",
    id: "aws",
  },
  {
    filename: "c++.svg",
    link: "https://docs.microsoft.com/en-us/cpp/?view=msvc-160",
    title: "C++",
    id: "c++",
  },
  {
    filename: "c.svg",
    link: "https://docs.microsoft.com/en-us/cpp/c-language/?view=msvc-160",
    title: "C",
    id: "c",
  },
  {
    filename: "docker.svg",
    link: "https://www.docker.com/",
    title: "Docker",
    id: "docker",
  },
  {
    filename: "drupal.svg",
    link: "https://www.drupal.org/",
    title: "Drupal",
    id: "drupal",
  },
  {
    filename: "electron.svg",
    link: "https://www.electronjs.org/",
    title: "ElectronJS",
    id: "electron",
  },
  {
    filename: "eslint.svg",
    link: "https://eslint.org/",
    title: "ESLint",
    id: "eslint",
  },
  {
    filename: "firestore.svg",
    link: "https://firebase.google.com/brand-guidelines",
    title: "Firestore",
    id: "firestore",
  },
  {
    filename: "git.svg",
    link: "https://git-scm.com/",
    title: "Git",
    id: "git",
  },
  {
    filename: "gradle.svg",
    link: "https://gradle.org/",
    title: "Gradle",
    id: "gradle",
  },
  {
    filename: "grafana.svg",
    link: "https://grafana.com/",
    title: "Grafana",
    id: "grafana",
  },
  {
    filename: "graphql.svg",
    link: "https://graphql.org/",
    title: "GraphQL",
    id: "graphql",
  },
  { filename: "grpc.svg", link: "https://grpc.io/", title: "gRPC", id: "grpc" },
  {
    filename: "hibernate.svg",
    link: "https://hibernate.org/",
    title: "Hibernate",
    id: "hibernate",
  },
  {
    filename: "influxdb.svg",
    link: "https://www.influxdata.com/",
    title: "InfluxDB",
    id: "influxdb",
  },
  {
    filename: "java.svg",
    link: "https://www.java.com/en/",
    title: "Java",
    id: "java",
  },
  {
    filename: "javascript.svg",
    link: "https://www.javascript.com/",
    title: "JavaScript",
    id: "javascript",
  },
  {
    filename: "jenkins.svg",
    link: "https://www.jenkins.io/",
    title: "Jenkins",
    id: "jenkins",
  },
  {
    filename: "jest.svg",
    link: "https://jestjs.io/",
    title: "Jest",
    id: "jest",
  },
  {
    filename: "kubernetes.svg",
    link: "https://kubernetes.io/",
    title: "Kubernetes",
    id: "kubernetes",
  },
  {
    filename: "maven.svg",
    link: "https://maven.apache.org/",
    title: "Maven",
    id: "maven",
  },
  {
    filename: "mongodb.svg",
    link: "https://www.mongodb.com/",
    title: "MongoDB",
    id: "mongodb",
  },
  {
    filename: "mui.svg",
    link: "https://material-ui.com/",
    title: "Material UI",
    id: "mui",
  },
  {
    filename: "mysql.svg",
    link: "https://www.mysql.com/",
    title: "MySQL",
    id: "mysql",
  },
  {
    filename: "nodejs.svg",
    link: "https://nodejs.org/en/",
    title: "NodeJS",
    id: "nodejs",
  },
  {
    filename: "postgresql.svg",
    link: "https://www.postgresql.org/",
    title: "PostgreSQL",
    id: "postgresql",
  },
  {
    filename: "prometheus.svg",
    link: "https://prometheus.io/",
    title: "Prometheus",
    id: "prometheus",
  },
  {
    filename: "python.svg",
    link: "https://www.python.org/",
    title: "Python",
    id: "python",
  },
  {
    filename: "react.svg",
    link: "https://reactjs.org/",
    title: "ReactJS",
    id: "react",
  },
  {
    filename: "rest.svg",
    link: "https://en.wikipedia.org/wiki/Representational_state_transfer",
    title: "REST API",
    id: "rest",
  },
  {
    filename: "ruby.svg",
    link: "https://www.ruby-lang.org/en/",
    title: "Ruby",
    id: "ruby",
  },
  {
    filename: "ruby_on_rails.svg",
    link: "https://rubyonrails.org/",
    title: "Ruby on Rails",
    id: "rubyonrails",
  },
  {
    filename: "spring.svg",
    link: "https://spring.io/",
    title: "Spring",
    id: "spring",
  },
  {
    filename: "tensorflow.svg",
    link: "https://www.tensorflow.org/",
    title: "Tensorflow",
    id: "tensorflow",
  },
  {
    filename: "travis.svg",
    link: "https://travis-ci.org/",
    title: "Travis",
    id: "travis",
  },
  {
    filename: "typescript.svg",
    link: "https://www.typescriptlang.org/",
    title: "TypeScript",
    id: "typescript",
  },
  {
    filename: "ue.svg",
    link: "https://www.unrealengine.com/",
    title: "Unreal Engine",
    id: "ue",
  },
  {
    filename: "wordpress.svg",
    link: "https://wordpress.com/",
    title: "WordPress",
    id: "wordpress",
  },
];
